"""
report.py
---------
Generates the TunnelScan report: ranked predictions, novel hypotheses,
calibration validation, and a complete landscape table.

The "novel predictions" section is the scientific output — a ranked list
of mutations that have never been experimentally tested, with predicted KIEs,
dominant mechanism, and experimental priority.
"""

import sys, os, datetime
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from tunnel_scan import ScanResult
from tunnel_score import MutationScore


def generate_report(result: ScanResult, output_path: str = None) -> str:
    """
    Generate the full TunnelScan report as a formatted string.
    Optionally saves to a file.
    """
    lines = []
    ts = datetime.datetime.now().strftime('%Y-%m-%d %H:%M')

    def h1(t): lines.append(f"\n{'█'*65}\n  {t}\n{'█'*65}")
    def h2(t): lines.append(f"\n{'─'*65}\n  {t}\n{'─'*65}")
    def hr():  lines.append('─' * 65)

    # ── Header ────────────────────────────────────────────────────────────────
    h1("TUNNELSCAN REPORT")
    lines.append(f"  Generated: {ts}")
    lines.append(f"  Enzyme:    {result.config.name}")
    lines.append(f"  PDB:       {result.config.pdb_id}")
    lines.append(f"  Residues scanned:      {result.n_residues_found}")
    lines.append(f"  Mutations predicted:   {result.n_mutations_scored}")
    lines.append(f"  Novel predictions:     {len(result.novel_scores)}")
    lines.append(f"  WT KIE (predicted):    {result.wt_kie_predicted:.1f}")
    lines.append(f"  WT KIE (experimental): {result.wt_kie_exp:.1f}")

    cal_r2 = result.calibration_r2
    if not np.isnan(cal_r2):
        lines.append(f"  Calibration R²:        {cal_r2:.3f}  (on {len(result.known_scores)} published mutants)")

    # ── Section 1: Calibration on known mutations ─────────────────────────────
    h2("SECTION 1 — Calibration: Known Mutations vs Experiment")
    lines.append(f"  {'Mutation':<10} {'Predicted':>10} {'Experimental':>13} {'Error':>8} {'Mechanism':<10}")
    hr()
    for sc in sorted(result.known_scores,
                     key=lambda x: x.experimental_kie or 0, reverse=True):
        if sc.experimental_kie is None:
            continue
        err_str = f"{sc.prediction_error*100:.0f}%" if sc.prediction_error else "  -"
        direction = "✓" if (
            (sc.predicted_kie < result.wt_kie_predicted) ==
            (sc.experimental_kie < result.wt_kie_exp)
        ) else "✗ direction wrong"
        lines.append(
            f"  {sc.label:<10} {sc.predicted_kie:>9.1f}  {sc.experimental_kie:>12.1f}  "
            f"{err_str:>7}   {sc.dominant_mechanism:<10} {direction}"
        )

    # ── Section 2: Top novel predictions ─────────────────────────────────────
    h2("SECTION 2 — ★ Novel Predictions (Never Experimentally Tested) ★")
    lines.append("  These mutations have not appeared in the published AADH literature.")
    lines.append("  They are ranked experimental hypotheses generated by TunnelScan.")
    lines.append("")

    top_enhancing = [s for s in result.novel_scores
                     if s.predicted_kie > result.wt_kie_predicted]
    top_reducing  = [s for s in result.novel_scores
                     if s.predicted_kie <= result.wt_kie_predicted]

    if top_enhancing:
        lines.append("  ◆ Mutations predicted to ENHANCE tunnelling above wild-type:")
        lines.append(f"  {'Mutation':<10} {'KIE':>6} {'vs WT':>7} {'Δstat':>7} {'Δdyn':>6} {'Mechanism':<10} {'Confidence':>10} {'Priority'}")
        hr()
        for sc in top_enhancing[:20]:
            lines.append(
                f"  {sc.label:<10} {sc.predicted_kie:>6.1f} "
                f"{sc.fold_vs_wt:>+6.2f}x "
                f"{sc.static_delta:>+6.2f} "
                f"{sc.dynamic_delta:>+5.2f}  "
                f"{sc.dominant_mechanism:<10} "
                f"{sc.confidence:>10.2f}  "
                f"{sc.priority()}"
            )

    lines.append("")
    lines.append("  ◆ Notable novel mutations predicted to reduce tunnelling:")
    lines.append("    (These confirm the dynamic model — useful as negative controls)")
    lines.append(f"  {'Mutation':<10} {'KIE':>6} {'vs WT':>7} {'Mechanism':<10} {'Why it reduces'}")
    hr()
    for sc in top_reducing[:10]:
        if sc.dynamic_delta < -0.3:
            reason = f"disrupts promoting vibration (disruption={sc.hbond_disruption:.1f})"
        elif sc.da_change > 0:
            reason = "elongates D-A distance (larger sidechain)"
        else:
            reason = "mixed effects"
        lines.append(
            f"  {sc.label:<10} {sc.predicted_kie:>6.1f} "
            f"{sc.fold_vs_wt:>+6.2f}x  "
            f"{sc.dominant_mechanism:<10} {reason}"
        )

    # ── Section 3: Mechanism breakdown ───────────────────────────────────────
    h2("SECTION 3 — Mechanism Analysis")

    static_dom  = [s for s in result.all_scores if s.dominant_mechanism=='static']
    dynamic_dom = [s for s in result.all_scores if s.dominant_mechanism=='dynamic']
    mixed_dom   = [s for s in result.all_scores if s.dominant_mechanism=='mixed']

    lines.append(f"  Static-dominated mutations:  {len(static_dom)}")
    lines.append(f"  Dynamic-dominated mutations: {len(dynamic_dom)}")
    lines.append(f"  Mixed-mechanism mutations:   {len(mixed_dom)}")
    lines.append("")

    top_static_novel = [s for s in static_dom
                        if s.is_novel and s.predicted_kie > result.wt_kie_predicted]
    if top_static_novel:
        lines.append("  Best static-only enhancers (safest to test — no dynamic risk):")
        for sc in top_static_novel[:5]:
            lines.append(f"    {sc.label:<10} KIE={sc.predicted_kie:.1f}  "
                         f"D-A compression={sc.da_change:+.3f}Å  conf={sc.confidence:.2f}")

    # ── Section 4: Full landscape table ──────────────────────────────────────
    h2("SECTION 4 — Complete Landscape (all mutations, sorted by KIE)")
    header = (f"  {'Mutation':<10} {'KIE':>6} {'fold':>7} {'Δstat':>7} "
              f"{'Δdyn':>6} {'mech':<10} {'imp':>5} {'conf':>5} "
              f"{'Novel':>6} {'Exp KIE':>8}")
    lines.append(header)
    hr()
    for sc in result.all_scores:
        exp_str = f"{sc.experimental_kie:.0f}" if sc.experimental_kie else "-"
        novel_str = "★" if sc.is_novel else " "
        lines.append(
            f"  {sc.label:<10} {sc.predicted_kie:>6.1f} "
            f"{sc.fold_vs_wt:>+6.2f}x "
            f"{sc.static_delta:>+6.2f} "
            f"{sc.dynamic_delta:>+5.2f}  "
            f"{sc.dominant_mechanism:<10} "
            f"{sc.dynamic_importance:>5.2f} "
            f"{sc.confidence:>5.2f} "
            f"{novel_str:>6} "
            f"{exp_str:>8}"
        )

    # ── Footer ────────────────────────────────────────────────────────────────
    h1("END OF REPORT")
    lines.append(f"  TunnelScan v0.1 | {ts}")
    lines.append(f"  Bell correction model. For quantitative accuracy, use PIMD (CP2K).")
    lines.append(f"  Novel predictions require experimental validation.")
    lines.append("")

    report = "\n".join(lines)

    if output_path:
        with open(output_path, 'w') as f:
            f.write(report)
        print(f"\n  Report saved to: {output_path}")

    return report


def print_quick_summary(result: ScanResult):
    """Print a short summary to terminal."""
    print(f"\n{'='*65}")
    print(f"  TUNNELSCAN SUMMARY — {result.config.pdb_id}")
    print(f"{'='*65}")
    print(f"  {result.n_mutations_scored} mutations scored  |  {len(result.novel_scores)} novel")
    print(f"  WT KIE: {result.wt_kie_predicted:.1f} (predicted) vs {result.wt_kie_exp:.1f} (experimental)")

    r2 = result.calibration_r2
    if not np.isnan(r2):
        print(f"  Calibration R² on known mutations: {r2:.3f}")

    print(f"\n  Top 10 mutations (all mechanisms):")
    print(f"  {'Label':<10} {'KIE':>6} {'fold':>7} {'mech':<10} {'novel'}")
    print(f"  {'─'*50}")
    for sc in result.all_scores[:10]:
        n = '★NOVEL★' if sc.is_novel else '       '
        print(f"  {sc.label:<10} {sc.predicted_kie:>6.1f} "
              f"{sc.fold_vs_wt:>+6.2f}x  {sc.dominant_mechanism:<10} {n}")

    enhancing_novel = result.top_enhancing
    if enhancing_novel:
        print(f"\n  ★ {len(enhancing_novel)} novel mutations predicted to exceed WT KIE ({result.wt_kie_predicted:.1f}):")
        for sc in enhancing_novel[:5]:
            print(f"    {sc.label:<10} KIE={sc.predicted_kie:.1f}  "
                  f"({sc.dominant_mechanism})  conf={sc.confidence:.2f}")
    print(f"{'='*65}\n")
